Get rid of most of the TypeScript errors
This was done with a plain old `npx tsc` and fixing the issues. Some were left
as they don't appear trivial and we, unfortunately, don't have the time to fix
them right now. As of this writing they are:

src/components/Hello/Hello.test.tsx:7:16 - error TS2339: Property 'mockResolvedValue' does not exist on type '{ (input: RequestInfo | URL, init?: RequestInit | undefined): Promise<Response>; (input: RequestInfo, init?: RequestInit | undefined): Promise<...>; }'.
src/test/setupAfterEnv.ts:6:16 - error TS2339: Property 'mockReset' does not exist on type '{ (input: RequestInfo | URL, init?: RequestInit | undefined): Promise<Response>; (input: RequestInfo, init?: RequestInit | undefined): Promise<...>; }'.
src/test/setupAfterEnv.ts:7:16 - error TS2339: Property 'mockImplementation' does not exist on type '{ (input: RequestInfo | URL, init?: RequestInit | undefined): Promise<Response>; (input: RequestInfo, init?: RequestInit | undefined): Promise<...>; }'.